-- Calculate monthly revenue trend to analyze business growth over time
-- This helps identify seasonality and overall performance trends
SELECT 
    DATE_TRUNC(order_date, MONTH) AS month,
    SUM(total) AS total_revenue,
    COUNT(DISTINCT order_id) AS total_orders
FROM work_bigquery.ecommerce
GROUP BY month
ORDER BY month;

-- Calculate the average order value (AOV)
-- This metric shows the average revenue generated by each order
SELECT 
    SUM(total) / COUNT(DISTINCT order_id) AS avg_order_value
FROM work_bigquery.ecommerce;

-- Analyze revenue distribution across product categories
-- Helps identify top-performing categories
SELECT 
    category,
    SUM(total) AS total_revenue,
    COUNT(DISTINCT order_id) AS total_orders
FROM work_bigquery.ecommerce
GROUP BY category
ORDER BY total_revenue DESC;

-- Identify top countries by revenue using subquery
-- This helps focus on the most profitable markets
SELECT *
FROM (
    SELECT 
        country,
        SUM(total) AS total_revenue
    FROM work_bigquery.ecommerce
    GROUP BY country
) t
ORDER BY total_revenue DESC
LIMIT 5;

-- Analyze delivery performance
-- Helps identify potential issues in order fulfillment
SELECT 
    delivery_status,
    COUNT(*) AS orders_count
FROM work_bigquery.ecommerce
GROUP BY delivery_status;



